# Generated by Django 2.2.8 on 2019-12-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0004_auto_20191214_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
