# Generated by Django 2.2.8 on 2019-12-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2mbasic', '0004_auto_20191220_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('friends', models.ManyToManyField(related_name='_facebookuser_friends_+', to='m2mbasic.FacebookUser')),
            ],
        ),
    ]
