# Generated by Django 2.2.8 on 2019-12-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2mbasic', '0005_facebookuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('counterpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_relation_set', to='m2mbasic.InstagramUser')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_relation_set', to='m2mbasic.InstagramUser')),
            ],
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='following',
            field=models.ManyToManyField(through='m2mbasic.Relation', to='m2mbasic.InstagramUser'),
        ),
    ]
