# Generated by Django 2.2.8 on 2019-12-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2mbasic', '0006_auto_20191221_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='m2mbasic.Relation', to='m2mbasic.InstagramUser'),
        ),
    ]
