# Generated by Django 2.2.8 on 2019-12-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customising_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
