# Generated by Django 2.2.8 on 2019-12-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
